# TODO: Do not require unstable features
# TODO: Maybe one day it will be possible to set:
# - max_width=80 but with wrapping when lines are too long at 72
# - function_brace_style = "AlwaysNextLine"
#   change brace_style only for functions

## Line Length
max_width = 72
comment_width = 72
doc_comment_code_block_width = 72

## Indentation and whitespace
hard_tabs = true
tab_spaces = 8
blank_lines_upper_bound = 2
newline_style = "Unix"

## Comments
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
wrap_comments = true

## Imports and modules
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Preserve"

## Braces
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

## Trailing commas and semicolons
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = true

## Multiline expressions
indent_style = "Block"
force_multiline_blocks = true
binop_separator = "Back"

## Other
use_field_init_shorthand = true
struct_lit_single_line = true
condense_wildcard_suffixes = true
hex_literal_case = "Upper"
