services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./make/init.sql:/docker-entrypoint-initdb.d/init.sql

  fish_populate:
    build: .
    container_name: fish-populate
    restart: no
    depends_on:
      - postgres
    environment:
      - PG_HOST=postgres
    command: ["./fish", "-P"]

  fish:
    build: .
    container_name: fish
    restart: unless-stopped
    depends_on:
      - postgres
      - fish_populate
    environment:
      - PG_HOST=postgres
    ports:
      - 3000:3000
